# Generated by Django 4.2.7 on 2023-11-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_text', models.TextField(verbose_name='Обращение')),
                ('category', models.TextField(verbose_name='Категория')),
                ('theme', models.TextField(verbose_name='Тема')),
                ('status', models.CharField(choices=[('CR', 'Created'), ('AC', 'Accepted'), ('RE', 'Rejected')], default='CR', max_length=2)),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
            },
        ),
    ]
