# Generated by Django 4.2.7 on 2023-11-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_theme', models.TextField()),
                ('theme', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='articles',
            name='name',
        ),
    ]
